[phases.setup]
nixPkgs = ["dotnet-sdk-9_0"]

[phases.build]
cmds = ["dotnet build src/Catalog.API/Catalog.API.csproj -c Release"]

[start]
cmd = "dotnet run --project src/Catalog.API/Catalog.API.csproj --urls http://0.0.0.0:8080"